name = "mpp-tx-scheduler"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["* * * * *"]  # every minute

[[d1_databases]]
binding = "DB"
database_name = "mpp-tx-scheduler"
database_id = "8e31411e-4ea7-4405-bacb-d6d8dddafc4e"

# MPP_SECRET_KEY and RECIPIENT_ADDRESS are set via `wrangler secret put`
[vars]
RPC_URL = "https://rpc.moderato.tempo.xyz"
